-- Run this in Supabase Dashboard > SQL Editor
-- Buka https://supabase.com/dashboard/project/[project-id]/sql/new

create table contacts (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  phone text,
  message text not null,
  created_at timestamptz default now()
);

alter table contacts enable row level security;

create policy "anon can insert contacts"
  on contacts for insert
  to anon
  with check (true);
